---

- name: Checking distribution
  fail:
    msg: "{{ ansible_distribution }} is not supported"
  when: ansible_distribution not in os_valid_distributions

- name: Checking version of OS
  fail:
    msg: "{{ ansible_distribution_version }} of {{ ansible_distribution }} is not supported"
  when: ansible_distribution_version is version_compare(os_minimum_versions[ansible_distribution], '<')

