---

- name: keepalived | install packages
  package:
    name: keepalived
  environment: '{{ proxy_env | default({}) }}'
  tags: [ keepalived_install, keepalived ]

- name: keepalived | make sure the kernel parameters "net.ipv4.ip_nonlocal_bind", "net.ipv4.ip_forward" are enabled
  sysctl:
    name: "{{ item }}"
    value: "1"
    sysctl_set: "yes"
    state: "present"
    reload: "yes"
  loop:
    - "net.ipv4.ip_nonlocal_bind"
    - "net.ipv4.ip_forward"
  tags: [ keepalived_conf, keepalived ]

- name: keepalived | generate conf file "/etc/keepalived/keepalived.conf"
  template:
    src: templates/keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
  tags: [ keepalived_conf, keepalived ]

- name: keepalived | restart systemd service
  systemd:
    daemon_reload: yes
    name: keepalived
    enabled: yes
    state: restarted
  tags: [ keepalived_restart, keepalived ]

- name: wait for the cluster ip address (VIP) "{{ cluster_vip }}" is running
  wait_for:
    host: "{{ cluster_vip }}"
    port: "{{ ansible_ssh_port }}"
    state: started
    timeout: 60
    delay: 2
  tags: [ keepalived_restart, keepalived ]
