---

  # Debian
- name: Generate locales "{% for set in locales %}{{ set.language_country }}.{{ set.encoding }}{% if not loop.last %},{% endif %}{% endfor %}"
  become: yes
  locale_gen:
    name: "{{ item.language_country }}.{{ item.encoding }}"
    state: present
  loop: "{{ locales | flatten(1) }}"
  when: ansible_os_family == "Debian"

  # RedHat
- name: Generate locales "{% for set in locales %}{{ set.language_country }}.{{ set.encoding }}{% if not loop.last %},{% endif %}{% endfor %}"
  become: yes
  command: localedef -c -i {{ item.language_country }} -f {{ item.encoding }} {{ item.language_country }}.{{ item.encoding }}
  changed_when: false
  loop: "{{ locales | flatten(1) }}"
  when: ansible_os_family == "RedHat"
