---

- name: PgBouncer | install package
  package:
    name: pgbouncer
  environment: '{{ proxy_env | default({}) }}'
  tags: [ pgbouncer_install, pgbouncer ]

- name: PgBouncer | ensure config directory "{{ pgbouncer_conf_dir }}" exist
  file:
    path: "{{ pgbouncer_conf_dir }}"
    state: directory
    owner: postgres
    group: postgres
    mode: 0750
  tags: [ pgbouncer_conf, pgbouncer ]

- name: PgBouncer | copy systemd service file
  template:
    src: templates/pgbouncer.service.j2
    dest: /etc/systemd/system/pgbouncer.service
    owner: postgres
    group: postgres
    mode: 0644
  tags: [ pgbouncer_service, pgbouncer ]

- name: PgBouncer | stop and disable standard init script
  service:
    name: pgbouncer
    state: stopped
    enabled: no
  tags: [ pgbouncer_service, pgbouncer ]

- name: PgBouncer | enable log rotation with logrotate
  copy:
    content: |
      /var/log/pgbouncer/pgbouncer.log {
             daily
             rotate 7
             copytruncate
             delaycompress
             compress
             notifempty
             missingok
             su root root
      }
    dest: /etc/logrotate.d/pgbouncer
  tags: [ pgbouncer_logrotate, pgbouncer ]

- name: PgBouncer | configure pgbouncer.ini
  template:
    src: templates/pgbouncer.ini.j2
    dest: "{{ pgbouncer_conf_dir }}/pgbouncer.ini"
    owner: postgres
    group: postgres
    mode: 0640
  tags: [ pgbouncer_conf, pgbouncer ]

- name: PgBouncer | configure userlist.txt
  template:
    src: templates/userlist.txt.j2
    dest: "{{ pgbouncer_conf_dir }}/userlist.txt"
    owner: postgres
    group: postgres
    mode: 0640
  tags: [ pgbouncer_conf, pgbouncer ]

- name: PgBouncer | restart systemd service
  systemd:
    daemon_reload: yes
    name: pgbouncer
    enabled: yes
    state: restarted
  tags: [ pgbouncer_restart, pgbouncer ]

- name: PgBouncer | wait for port "{{ pgbouncer_listen_port }}" to become open on the host
  wait_for:
    port: "{{ pgbouncer_listen_port }}"
    host: "{{ hostvars[inventory_hostname]['inventory_hostname'] }}"
    state: started
    timeout: 300
    delay: 5
  ignore_errors: no
  tags: [ pgbouncer_restart, pgbouncer ]
