---

- name: sudo | add postgres user to the /etc/sudoers.d/postgres
  copy:
    dest: "/etc/sudoers.d/postgres"
    content: "postgres  ALL=(ALL)  NOPASSWD: ALL"
  tags: sudo

- name: enable SSH forwarding for sudo
  lineinfile:
    dest: /etc/sudoers
    insertafter: '^#?\s*Defaults\s+env_keep\b'
    line: 'Defaults    env_keep += "SSH_AUTH_SOCK"'